### ISSUE TITLE
It seems to be no way of launching a command on save

### ISSUE THREAD

**Issue by vidal7** [richie5um/vscode-sort-json#22]
Hi, for a particular project, we need to maintain JSON files in alphabetical order. This plugin is very great for that but we need to call command sortJSON.sortJSON everytime before saving. If there was a way yo trigger it automatically onSave, that will be a major time saving.

Thanks!

**Comment by richie5um** [comment]
I'm not entirely sure if you can do that with VSCode extensions.

One alternative would be to use 'jq' - and integrate that into your build / git process. Like this:
`jq --sort-keys . myfile.json`

[JQ - Cmd Line JSON Processor](https://stedolan.github.io/jq/) 

Let me know if that doesn't fit for what you need and I'll do some more investigating.

**Comment by vidal7** [comment]
Thank you. Maybe I can trigger the command with a VS Code plugin on save like https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave.

But again, it will be very nice to have sortJSON.sortJSON run automatically on saving json files.

**Comment by andraaspar** [comment]
It should be possible to create a code action which can then be added to `"editor.codeActionsOnSave"` in your settings. Please see [this comment](https://github.com/Microsoft/vscode/issues/50275#issuecomment-391488399).

**Comment by richie5um** [comment]
Thank you. I'll take a look.

**Comment by FlorianWendelborn** [comment]
@richie5um I realize that everyone is busy nowadays, I figured it’d still be good to ask: Is there any (current or expected) progress on this issue? I’ve never written a vscode plugin unfortunately, but I’d imagine that modifying it to be usable with `editor.codeActionsOnSave` shouldn’t be that hard.

Thanks for the great package in any case. I’m still surprised that prettier can’t do this.

**Comment by JerryGreen** [comment]
Continue updating the issue once a year, huh? I've never written vscode extension either, but let's take a look at existing examples at least: tslint already has such a feature for quite a long time. We look at those ones particularly interesting rows:

<a href="https://github.com/microsoft/vscode-typescript-tslint-plugin/blob/c3ec940ff64e7058ef142ed7f36f7127b3a5a7d1/src/index.ts#L40-L47" target="_blank">

```ts
    const selector: vscode.DocumentFilter[] = [];
    for (const language of ['javascript', 'javascriptreact', 'typescript', 'typescriptreact']) {
        selector.push({ language, scheme: 'file' });
        selector.push({ language, scheme: 'untitled' });
    }


    context.subscriptions.push(
        vscode.languages.registerCodeActionsProvider(selector, new FixAllProvider(), FixAllProvider.metadata));
```
</a>

But all the magic happens in `FixAllProvider`, it seems, so we look there. There's indeed an interesting row, similar to the one described here https://github.com/Microsoft/vscode/issues/50275#issuecomment-391488399 (thks @andraaspar for the link):

<a href="https://github.com/microsoft/vscode-typescript-tslint-plugin/blob/c3ec940ff64e7058ef142ed7f36f7127b3a5a7d1/src/fixAll.ts#L27">

```ts
    public static readonly fixAllCodeActionKind = vscode.CodeActionKind.SourceFixAll.append('tslint');
```
</a>

Ok, so we have a hotkey, but how to glue it all together, with the existing command? Well, there's another interesting vscode call in the code, `vscode.commands.executeCommand`:

<a href="https://github.com/microsoft/vscode-typescript-tslint-plugin/blob/c3ec940ff64e7058ef142ed7f36f7127b3a5a7d1/src/fixAll.ts#L5-L7">

```ts
function executeCodeActionProvider(uri: vscode.Uri, range: vscode.Range) {
    return vscode.commands.executeCommand<vscode.CodeAction[]>('vscode.executeCodeActionProvider', uri, range);
}
```
</a>

Since we already have in `vscode-sort-json` repo:

https://github.com/richie5um/vscode-sort-json/blob/39efa9eb751ae565c31d26b2cf46a223f058794e/lib/index.js#L6-L9

Now we need some actual code changes here :) I may make some PR soon, but not sure

**Comment by vidal7** [comment]
Thanks a lot. It works brilliantly.
