### ISSUE TITLE
Allow user to deactivate contextual menu entries

### ISSUE THREAD

**Issue by alk-mgesbert** [richie5um/vscode-sort-json#32]
Hello, I recently noticed that the number of entries in the contextual menu has greatly increased:
![image](https://user-images.githubusercontent.com/50456439/67699271-30cdde00-f9ac-11e9-9108-db5d291c4b45.png)
I thinks it's a lot, would you mind adding a setting to allow the user to remove these entries?

**Comment by Guduche** [comment]
You can do it with the setting `sortJSON.contextMenu`.

You can add this in your `settings.json` (every default value is `true`) :

```json
"sortJSON.contextMenu": {
    "sortJSON": false,
    "sortJSONAlphaNum": false,
    "sortJSONAlphaNumReverse": false,
    "sortJSONKeyLength": false,
    "sortJSONKeyLengthReverse": false,
    "sortJSONReverse": false,
    "sortJSONType": false,
    "sortJSONTypeReverse": false,
    "sortJSONValues": false,
    "sortJSONValuesReverse": false
}
```

**Comment by Shoelace** [comment]
great.. just what i was looking for.  maybe add it to the "settings" manual  (ie https://github.com/richie5um/vscode-sort-json#settings ) so people can find it easier

the other option would be to move them to a submenu.. but since you can access all the sort options via the command window (ctrl-shift-p) thats not super needed

**Comment by richie5um** [comment]
Thanks to both of you! I'll update the readme.
